services:
  mysql:
    container_name: mysql
    image: mysql:9.1
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: example_dev
      MYSQL_USER: example
      MYSQL_PASSWORD: my-secret-pw
    ports:
      - '3306:3306'
